// Package brandassets holds no code — only a guard over the brand glyph.
//
// The Keystone Arch path is duplicated by necessity: React components import it
// from the SDK, but the standalone SVGs and the marketing site's inline markup
// cannot, so each carries its own copy. Nothing linked those copies together,
// which is how the white-label preview came to render a letter "O" months after
// the shell had moved to the arch.
//
// This is a Go test on purpose. The copies span the SDK (TS), web/public (SVG)
// and website (Astro), so no single frontend test runner sees all of them —
// and `go test ./...` always runs in CI.
package brandassets

import (
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// archPathRe pulls the ARCH_PATH constant out of the SDK's brand module, which
// is the single source of truth every other copy must match.
var archPathRe = regexp.MustCompile(`(?s)ARCH_PATH\s*=\s*\n?\s*"([^"]+)"`)

// copies are the files carrying a hand-maintained duplicate of the arch path.
// webembed/dist is deliberately absent: it is a build artefact, regenerated by
// CI from web/, so asserting on it would just report a stale build.
var copies = []string{
	"web/public/logo-mark.svg",
	"web/public/logo-mark-mono.svg",
	"website/src/components/Header.astro",
}

func repoRoot(t *testing.T) string {
	t.Helper()
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatalf("resolve repo root: %v", err)
	}
	return root
}

func TestArchPathCopiesAreInSync(t *testing.T) {
	root := repoRoot(t)

	src := filepath.Join(root, "packages/plugin-sdk/src/brand/index.tsx")
	b, err := os.ReadFile(src)
	if err != nil {
		t.Fatalf("read the canonical glyph: %v", err)
	}
	m := archPathRe.FindSubmatch(b)
	if m == nil {
		t.Fatalf("no ARCH_PATH constant in %s — did the glyph move? every copy below is now unguarded", src)
		return
	}
	canonical := string(m[1])

	for _, rel := range copies {
		t.Run(rel, func(t *testing.T) {
			b, err := os.ReadFile(filepath.Join(root, rel))
			if err != nil {
				t.Fatalf("read copy: %v", err)
			}
			if !strings.Contains(string(b), canonical) {
				t.Errorf("%s does not carry the current arch path.\nExpected to find:\n  %s\nUpdate it, or the brand renders differently here than in the app.", rel, canonical)
			}
		})
	}
}
