import { lazy } from "react";
import type { UIPlugin } from "@octarq/plugin-sdk";

const HelpViewer = lazy(() => import("./HelpViewer"));

export default {
  name: "help",
  i18n: {
    en: {
      _shared: {
        nav: { help: "Help" },
      },
      title: "Help & Documentation",
      loading: "Loading documentation…",
      empty: "No documentation available.",
      search_placeholder: "Search docs (press '/' to focus)…",
      platform_title: "Platform Core",
      platform_subtitle: "Essential system capabilities & specs",
      plugin_title: "Plugin Extensions",
      plugin_subtitle: "Modular services & extra features",
      all_categories: "All Docs",
      on_this_page: "On this page",
      prev_doc: "Previous Doc",
      next_doc: "Next Doc",
      copy_code: "Copy",
      copied: "Copied!",
      no_results: "No documents match your search.",
      read_time: "min read",
      copy_page_link: "Copy Page Link",
      feedback_title: "Was this page helpful?",
      feedback_thanks: "Thank you for your feedback!",
      helpful: "Helpful",
      unhelpful: "Needs improvement",
      scope_platform: "Platform Core",
      scope_portal: "Portal & Workspace",
      scope_plugins: "Plugin Extensions",
      cat_general: "Getting Started & Overview",
      cat_security: "Authentication & Tokens",
      cat_portal: "Multi-tenant & Workspaces",
      cat_workspace: "Multi-tenant & Workspaces",
      cat_ai: "AI & MCP Protocol",
      cat_events: "Event Bus & Webhooks",
      cat_links: "Short Links",
      cat_dns: "DNS & Domain Management",
      cat_mail: "Mailboxes & Email Routing",
      cat_marketing: "Marketing Tools",
      cat_infra: "Network & Infrastructure",
      cat_messaging: "Messaging & Communication",
    },
    zh: {
      _shared: {
        nav: { help: "帮助" },
      },
      title: "帮助与开发文档",
      loading: "加载文档中…",
      empty: "暂无可用文档。",
      search_placeholder: "搜索文档 (按 '/' 快速定位)…",
      platform_title: "平台能力",
      platform_subtitle: "核心系统能力与通用标准",
      plugin_title: "插件能力",
      plugin_subtitle: "模块化扩展与相关服务",
      all_categories: "全部文档",
      on_this_page: "本文目录",
      prev_doc: "上一篇",
      next_doc: "下一篇",
      copy_code: "复制",
      copied: "已复制！",
      no_results: "未找到匹配的文档。",
      read_time: "分钟阅读",
      copy_page_link: "复制页面链接",
      feedback_title: "这份文档对您有帮助吗？",
      feedback_thanks: "感谢您的反馈！",
      helpful: "有帮助",
      unhelpful: "需改进",
      scope_platform: "平台核心",
      scope_portal: "门户与工作区",
      scope_plugins: "插件扩展",
      cat_general: "概览与入门指南",
      cat_security: "身份认证与 Token",
      cat_portal: "多组织架构与工作区",
      cat_workspace: "多组织架构与工作区",
      cat_ai: "AI 与 MCP 协议",
      cat_events: "事件中心与 Webhooks",
      cat_links: "短链接服务",
      cat_dns: "域名与 DNS 服务",
      cat_mail: "邮箱与邮件路由",
      cat_marketing: "营销工具",
      cat_infra: "网络与基础设施",
      cat_messaging: "消息与通讯服务",
    },
    es: {
      _shared: {
        nav: { help: "Ayuda" },
      },
      title: "Ayuda y Documentación",
      loading: "Cargando documentación…",
      empty: "No hay documentación disponible.",
      search_placeholder: "Buscar documentación…",
      platform_title: "Capacidades de la Plataforma",
      platform_subtitle: "Capacidades básicas del sistema",
      plugin_title: "Capacidades de Complementos",
      plugin_subtitle: "Servicios modulares",
      all_categories: "Todos",
      on_this_page: "En esta página",
      prev_doc: "Anterior",
      next_doc: "Siguiente",
      copy_code: "Copiar",
      copied: "¡Copiado!",
      no_results: "No se encontraron documentos.",
      read_time: "min de lectura",
      copy_page_link: "Copiar enlace de la página",
      feedback_title: "¿Te ha sido útil esta página?",
      feedback_thanks: "¡Gracias por tus comentarios!",
      helpful: "Útil",
      unhelpful: "Necesita mejorar",
      scope_platform: "Núcleo de Plataforma",
      scope_portal: "Portal y Espacio de Trabajo",
      scope_plugins: "Extensiones",
      cat_general: "Inicio rápido y visión general",
      cat_security: "Autenticación y Tokens",
      cat_portal: "Multiorganización y Espacios",
      cat_workspace: "Multiorganización y Espacios",
      cat_ai: "Protocolo IA y MCP",
      cat_events: "Eventos y Webhooks",
      cat_links: "Servicio de enlaces cortos",
      cat_dns: "Gestión de DNS y Dominios",
      cat_mail: "Buzones y Enrutamiento de Email",
      cat_marketing: "Herramientas de Marketing",
      cat_infra: "Red e Infraestructura",
      cat_messaging: "Mensajería y Comunicación",
    },
    pt: {
      _shared: {
        nav: { help: "Ajuda" },
      },
      title: "Ajuda e Documentação",
      loading: "Carregando documentação…",
      empty: "Nenhuma documentação disponível.",
      search_placeholder: "Pesquisar documentação…",
      platform_title: "Capacidades da Plataforma",
      platform_subtitle: "Recursos essenciais do sistema",
      plugin_title: "Capacidades de Plugins",
      plugin_subtitle: "Serviços modulares",
      all_categories: "Todos",
      on_this_page: "Nesta página",
      prev_doc: "Anterior",
      next_doc: "Próximo",
      copy_code: "Copiar",
      copied: "Copiado!",
      no_results: "Nenhum documento encontrado.",
      read_time: "min de leitura",
      copy_page_link: "Copiar link da página",
      feedback_title: "Esta página foi útil?",
      feedback_thanks: "Obrigado pelo seu feedback!",
      helpful: "Útil",
      unhelpful: "Precisa melhorar",
      scope_platform: "Núcleo da Plataforma",
      scope_portal: "Portal e Espaço de Trabalho",
      scope_plugins: "Extensões de Plugins",
      cat_general: "Primeiros passos e Visão geral",
      cat_security: "Autenticação e Tokens",
      cat_portal: "Multi-organização e Espaços",
      cat_workspace: "Multi-organização e Espaços",
      cat_ai: "IA e Protocolo MCP",
      cat_events: "Barramento de Eventos e Webhooks",
      cat_links: "Serviço de Links Curtos",
      cat_dns: "Gerenciamento de DNS e Domínio",
      cat_mail: "Caixas de Correio e Roteamento",
      cat_marketing: "Ferramentas de Marketing",
      cat_infra: "Rede e Infraestrutura",
      cat_messaging: "Mensagens e Comunicação",
    },
    ja: {
      _shared: {
        nav: { help: "ヘルプ" },
      },
      title: "ヘルプとドキュメント",
      loading: "ドキュメントを読み込み中…",
      empty: "利用できるドキュメントはありません。",
      search_placeholder: "ドキュメントを検索…",
      platform_title: "プラットフォーム機能",
      platform_subtitle: "基本システム機能",
      plugin_title: "プラグイン機能",
      plugin_subtitle: "モジュールサービス",
      all_categories: "すべて",
      on_this_page: "このページの内容",
      prev_doc: "前へ",
      next_doc: "次へ",
      copy_code: "コピー",
      copied: "コピーしました！",
      no_results: "一致するドキュメントはありません。",
      read_time: "分で読める",
      copy_page_link: "ページリンクをコピー",
      feedback_title: "このページは役に立ちましたか？",
      feedback_thanks: "フィードバックありがとうございます！",
      helpful: "役に立った",
      unhelpful: "改善が必要",
      scope_platform: "プラットフォーム機能",
      scope_portal: "ポータル＆ワークスペース",
      scope_plugins: "プラグイン拡張",
      cat_general: "クイックスタートと概要",
      cat_security: "認証とトークン",
      cat_portal: "マルチ組織とワークスペース",
      cat_workspace: "マルチ組織とワークスペース",
      cat_ai: "AI & MCP プロトコル",
      cat_events: "イベントバス & Webhook",
      cat_links: "短縮 URL サービス",
      cat_dns: "DNS & ドメイン管理",
      cat_mail: "メールボックス & ルーティング",
      cat_marketing: "マーケティングツール",
      cat_infra: "ネットワーク & インフラ",
      cat_messaging: "メッセージング & 通信",
    },
  },
  routes: [
    { path: "/help", Component: HelpViewer },
    { path: "/help/*", Component: HelpViewer },
    { path: "/admin/help", Component: HelpViewer },
    { path: "/admin/help/*", Component: HelpViewer },
  ],
} satisfies UIPlugin;
