import { lazy } from "react";
import type { UIPlugin } from "@octarq/plugin-sdk";

const HelpViewer = lazy(() => import("./HelpViewer"));

export default {
  name: "help",
  // The `help` namespace backs HelpViewer. It used to be absent entirely — the
  // viewer passed English fallbacks to t(), which renders correctly in every
  // locale and so looks translated while it isn't. Keep the keys here so a
  // missing locale is a visible gap rather than silent English.
  i18n: {
    en: {
      _shared: {
        nav: { help: "Help" },
      },
      title: "Help & Documentation",
      loading: "Loading documentation…",
      empty: "No documentation available.",
      search_placeholder: "Search docs (press '/' to focus)…",
      platform_title: "Platform Core",
      platform_subtitle: "Essential system capabilities & specs",
      plugin_title: "Plugin Extensions",
      plugin_subtitle: "Modular services & extra features",
      all_categories: "All Docs",
      on_this_page: "On this page",
      prev_doc: "Previous Doc",
      next_doc: "Next Doc",
      copy_code: "Copy",
      copied: "Copied!",
      no_results: "No documents match your search.",
      read_time: "min read",
    },
    zh: {
      _shared: {
        nav: { help: "帮助" },
      },
      title: "帮助与开发文档",
      loading: "加载文档中…",
      empty: "暂无可用文档。",
      search_placeholder: "搜索文档 (按 '/' 快速定位)…",
      platform_title: "平台能力",
      platform_subtitle: "核心系统能力与通用标准",
      plugin_title: "插件能力",
      plugin_subtitle: "模块化扩展与相关服务",
      all_categories: "全部文档",
      on_this_page: "本文目录",
      prev_doc: "上一篇",
      next_doc: "下一篇",
      copy_code: "复制",
      copied: "已复制！",
      no_results: "未找到匹配的文档。",
      read_time: "分钟阅读",
    },
    es: {
      _shared: {
        nav: { help: "Ayuda" },
      },
      title: "Ayuda y Documentación",
      loading: "Cargando documentación…",
      empty: "No hay documentación disponible.",
      search_placeholder: "Buscar documentación…",
      platform_title: "Capacidades de la Plataforma",
      platform_subtitle: "Capacidades básicas del sistema",
      plugin_title: "Capacidades de Complementos",
      plugin_subtitle: "Servicios modulares",
      all_categories: "Todos",
      on_this_page: "En esta página",
      prev_doc: "Anterior",
      next_doc: "Siguiente",
      copy_code: "Copiar",
      copied: "¡Copiado!",
      no_results: "No se encontraron documentos.",
      read_time: "min de lectura",
    },
    pt: {
      _shared: {
        nav: { help: "Ajuda" },
      },
      title: "Ajuda e Documentação",
      loading: "Carregando documentação…",
      empty: "Nenhuma documentação disponível.",
      search_placeholder: "Pesquisar documentação…",
      platform_title: "Capacidades da Plataforma",
      platform_subtitle: "Recursos essenciais do sistema",
      plugin_title: "Capacidades de Plugins",
      plugin_subtitle: "Serviços modulares",
      all_categories: "Todos",
      on_this_page: "Nesta página",
      prev_doc: "Anterior",
      next_doc: "Próximo",
      copy_code: "Copiar",
      copied: "Copiado!",
      no_results: "Nenhum documento encontrado.",
      read_time: "min de leitura",
    },
    ja: {
      _shared: {
        nav: { help: "ヘルプ" },
      },
      title: "ヘルプとドキュメント",
      loading: "ドキュメントを読み込み中…",
      empty: "利用できるドキュメントはありません。",
      search_placeholder: "ドキュメントを検索…",
      platform_title: "プラットフォーム機能",
      platform_subtitle: "基本システム機能",
      plugin_title: "プラグイン機能",
      plugin_subtitle: "モジュールサービス",
      all_categories: "すべて",
      on_this_page: "このページの内容",
      prev_doc: "前へ",
      next_doc: "次へ",
      copy_code: "コピー",
      copied: "コピーしました！",
      no_results: "一致するドキュメントはありません。",
      read_time: "分で読める",
    },
  },
  routes: [
    { path: "/help", Component: HelpViewer },
    { path: "/help/*", Component: HelpViewer },
    { path: "/admin/help", Component: HelpViewer },
    { path: "/admin/help/*", Component: HelpViewer },
  ],
} satisfies UIPlugin;
