import { lazy } from "react";
import type { UIPlugin } from "@octarq/plugin-sdk";

const HelpViewer = lazy(() => import("./HelpViewer"));

export default {
  name: "help",
  i18n: {
    en: {
      _shared: {
        nav: { help: "Help" },
      },
      title: "Help & Documentation",
      loading: "Loading documentation…",
      platform_subtitle: "Essential system capabilities & specs",
      on_this_page: "On this page",
      prev_doc: "Previous Doc",
      next_doc: "Next Doc",
      copy_code: "Copy",
      copied: "Copied!",
      read_time: "min read",
      copy_page_link: "Copy Page Link",
      callout_tip: "TIP",
      callout_warning: "WARNING",
      callout_important: "IMPORTANT",
      callout_note: "NOTE",
      not_found_title: "That page isn't in this build",
      not_found_body: "No documentation is installed under this address. The plugin that owns it may not be part of this edition, or the page may have been renamed.",
      not_found_action: "Browse the documentation index",
    },
    zh: {
      _shared: {
        nav: { help: "帮助" },
      },
      title: "帮助与开发文档",
      loading: "加载文档中…",
      platform_subtitle: "核心系统能力与通用标准",
      on_this_page: "本文目录",
      prev_doc: "上一篇",
      next_doc: "下一篇",
      copy_code: "复制",
      copied: "已复制！",
      read_time: "分钟阅读",
      copy_page_link: "复制页面链接",
      callout_tip: "提示",
      callout_warning: "警告",
      callout_important: "注意",
      callout_note: "说明",
      not_found_title: "此版本未包含该页面",
      not_found_body: "该地址下没有已安装的文档。它所属的插件可能不在当前版本中，或者页面已被重命名。",
      not_found_action: "浏览文档目录",
    },
    es: {
      _shared: {
        nav: { help: "Ayuda" },
      },
      title: "Ayuda y Documentación",
      loading: "Cargando documentación…",
      platform_subtitle: "Capacidades básicas del sistema",
      on_this_page: "En esta página",
      prev_doc: "Anterior",
      next_doc: "Siguiente",
      copy_code: "Copiar",
      copied: "¡Copiado!",
      read_time: "min de lectura",
      copy_page_link: "Copiar enlace de la página",
      callout_tip: "CONSEJO",
      callout_warning: "ADVERTENCIA",
      callout_important: "IMPORTANTE",
      callout_note: "NOTA",
      not_found_title: "Esa página no está en esta edición",
      not_found_body: "No hay documentación instalada en esta dirección. El plugin que la contiene puede no formar parte de esta edición, o la página fue renombrada.",
      not_found_action: "Ver el índice de documentación",
    },
    pt: {
      _shared: {
        nav: { help: "Ajuda" },
      },
      title: "Ajuda e Documentação",
      loading: "Carregando documentação…",
      platform_subtitle: "Recursos essenciais do sistema",
      on_this_page: "Nesta página",
      prev_doc: "Anterior",
      next_doc: "Próximo",
      copy_code: "Copiar",
      copied: "Copiado!",
      read_time: "min de leitura",
      copy_page_link: "Copiar link da página",
      callout_tip: "DICA",
      callout_warning: "AVISO",
      callout_important: "IMPORTANTE",
      callout_note: "NOTA",
      not_found_title: "Essa página não está nesta edição",
      not_found_body: "Não há documentação instalada neste endereço. O plugin que a contém pode não fazer parte desta edição, ou a página foi renomeada.",
      not_found_action: "Ver o índice da documentação",
    },
    ja: {
      _shared: {
        nav: { help: "ヘルプ" },
      },
      title: "ヘルプとドキュメント",
      loading: "ドキュメントを読み込み中…",
      platform_subtitle: "基本システム機能",
      on_this_page: "このページの内容",
      prev_doc: "前へ",
      next_doc: "次へ",
      copy_code: "コピー",
      copied: "コピーしました！",
      read_time: "分で読める",
      copy_page_link: "ページリンクをコピー",
      callout_tip: "ヒント",
      callout_warning: "警告",
      callout_important: "重要",
      callout_note: "注记",
      not_found_title: "このビルドには該当ページがありません",
      not_found_body: "このアドレスにドキュメントはインストールされていません。該当プラグインがこのエディションに含まれていないか、ページ名が変更された可能性があります。",
      not_found_action: "ドキュメント一覧を開く",
    },
  },
  routes: [
    { path: "/help", Component: HelpViewer },
    { path: "/help/*", Component: HelpViewer },
  ],
} satisfies UIPlugin;
