// Command octarq-build wires third-party plugins into a custom Octarq binary at
// build time — the xcaddy model: pick plugins, build a binary. It is driven by
// `make plugin-build` (or a Docker build) and is not something end users run
// directly.
//
// It reads the OCTARQ_PLUGINS manifest from the environment: a JSON array where
// each entry describes one plugin,
//
//	[
//	  {
//	    "go":   "github.com/you/octarq-plugin-foo",          // Go import path of the package exporting Plugin (backend half)
//	    "gomod":"github.com/you/octarq-plugin-foo@v1.2.0",   // optional; module@version for `go get` (default: <go>@latest)
//	    "npm":  "@you/octarq-plugin-foo"                     // optional; npm specifier of the UI half (frontend)
//	  }
//	]
//
// and then:
//
//  1. runs `go get` for each backend module (so go.mod resolves it),
//  2. regenerates ./custom_plugins.go with an aliased import + `&Plugin{}` entry
//     per backend plugin (relies on the convention that every Octarq plugin
//     package exports a `Plugin` type), and
//  3. writes ./.octarq-frontend-plugins.json — the JSON array of npm specifiers
//     the frontend build consumes via its own OCTARQ_PLUGINS manifest.
//
// Reset a working tree afterwards with:
//
//	git checkout custom_plugins.go go.mod go.sum && rm -f .octarq-frontend-plugins.json
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"strings"
)

type entry struct {
	Go    string `json:"go"`
	GoMod string `json:"gomod"`
	NPM   string `json:"npm"`
}

const (
	genFile      = "custom_plugins.go"
	frontendFile = ".octarq-frontend-plugins.json"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "octarq-build:", err)
		os.Exit(1)
	}
}

func run() error {
	raw := strings.TrimSpace(os.Getenv("OCTARQ_PLUGINS"))
	if raw == "" {
		return fmt.Errorf("OCTARQ_PLUGINS is empty; set it to a JSON array of plugin entries")
	}
	var entries []entry
	if err := json.Unmarshal([]byte(raw), &entries); err != nil {
		return fmt.Errorf("parsing OCTARQ_PLUGINS: %w", err)
	}

	var (
		backend  []entry
		frontend []string
	)
	for _, e := range entries {
		if e.Go != "" {
			backend = append(backend, e)
		}
		if e.NPM != "" {
			frontend = append(frontend, e.NPM)
		}
	}

	// 1. Resolve each backend module into go.mod.
	for _, e := range backend {
		target := e.GoMod
		if target == "" {
			target = e.Go + "@latest"
		}
		fmt.Fprintln(os.Stderr, "octarq-build: go get", target)
		cmd := exec.Command("go", "get", target)
		cmd.Stdout, cmd.Stderr = os.Stderr, os.Stderr
		if err := cmd.Run(); err != nil {
			return fmt.Errorf("go get %s: %w", target, err)
		}
	}

	// 2. Regenerate custom_plugins.go.
	if err := writeBackend(backend); err != nil {
		return err
	}

	// 3. Emit the frontend manifest (always valid JSON, even if empty).
	if frontend == nil {
		frontend = []string{}
	}
	feJSON, err := json.Marshal(frontend)
	if err != nil {
		return err
	}
	if err := os.WriteFile(frontendFile, append(feJSON, '\n'), 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", frontendFile, err)
	}

	fmt.Fprintf(os.Stderr, "octarq-build: wired %d backend, %d frontend plugin(s)\n", len(backend), len(frontend))
	return nil
}

func writeBackend(backend []entry) error {
	var b strings.Builder
	b.WriteString("// Code generated by cmd/octarq-build; DO NOT EDIT.\n")
	b.WriteString("// Reset with: git checkout custom_plugins.go go.mod go.sum\n\n")
	b.WriteString("package main\n\n")
	b.WriteString("import (\n\t\"github.com/octarq-org/octarq/plugin\"\n")
	for i, e := range backend {
		fmt.Fprintf(&b, "\n\tp%d %q", i, e.Go)
	}
	b.WriteString("\n)\n\n")
	b.WriteString("func customPlugins() []plugin.Plugin {\n")
	if len(backend) == 0 {
		b.WriteString("\treturn nil\n}\n")
	} else {
		b.WriteString("\treturn []plugin.Plugin{\n")
		for i := range backend {
			fmt.Fprintf(&b, "\t\t&p%d.Plugin{},\n", i)
		}
		b.WriteString("\t}\n}\n")
	}

	src, err := format.Source([]byte(b.String()))
	if err != nil {
		return fmt.Errorf("formatting generated %s: %w", genFile, err)
	}
	if err := os.WriteFile(genFile, src, 0o644); err != nil {
		return fmt.Errorf("writing %s: %w", genFile, err)
	}
	return nil
}
