package main

import (
	"fmt"
	"os"

	"github.com/octarq-org/octarq/openapi"
)

// This command generates the core (plugin-free) OpenAPI specification.
// Its purpose is to allow local viewing of the core API surface.
// The authoritative, published specification is generated by octarq-pro's
// `octarq-pro openapi` command (which includes all pro plugins) and is
// refreshed by .github/workflows/openapi.yml in that repository.
// They are not the same thing, and this tool writes to stdout so it
// does not overwrite the pro repository's file.
func main() {
	// In the standalone generator, no plugins are passed (nil)
	if err := openapi.Generate(os.Stdout, nil); err != nil {
		fmt.Fprintf(os.Stderr, "Error generating spec: %v\n", err)
		os.Exit(1)
	}
}
